version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: leal
      POSTGRES_PASSWORD: lealpassword
      POSTGRES_DB: api_node_fazt_tutorial
    ports:
      - 5432:5432